.ALIASES
V_V1            V1(+=N00238 -=0 ) CN @BAI 5.SCHEMATIC1(sch_1):INS35@SOURCE.VDC.Normal(chips)
R_R1            R1(1=0 2=N00238 ) CN @BAI 5.SCHEMATIC1(sch_1):INS60@ANALOG.R.Normal(chips)
R_R2            R2(1=N00219 2=N00227 ) CN @BAI 5.SCHEMATIC1(sch_1):INS76@ANALOG.R.Normal(chips)
V_V2            V2(+=N00219 -=0 ) CN @BAI 5.SCHEMATIC1(sch_1):INS117@SOURCE.VDC.Normal(chips)
L_L1            L1(1=N00808 2=0 ) CN @BAI 5.SCHEMATIC1(sch_1):INS192@ANALOG.L.Normal(chips)
R_R3            R3(1=N00808 2=N00227 ) CN @BAI 5.SCHEMATIC1(sch_1):INS778@ANALOG.R.Normal(chips)
X_S1            S1(1=N00238 2=N00227 ) CN @BAI 5.SCHEMATIC1(sch_1):INS995@EVAL.Sw_tClose.Normal(chips)
.ENDALIASES
